### PR TITLE
Fix pyproject.toml

### PR DESCRIPTION
**Pull request by larryliu0820**
Include both files and subdirectory under `torch_np`.

### CODE REVIEW

**Comment by honno** [comment]
Weird, yeah the previous pyproject won't build the files directly under `torch_np/` for the wheel, but will for the tarball (when using `python -m build`). LGTM

@larryliu0820 out of curiousity, why would one include a `setup.py` if using `pyproject.toml`?

**Comment by larryliu0820** [comment]
> Weird, yeah the previous pyproject won't build the files directly under `torch_np/` for the wheel, but will for the tarball (when using `python -m build`). LGTM
> 
> @larryliu0820 out of curiousity, why would one include a `setup.py` if using `pyproject.toml`?

Yeah `pyproject.toml` is still in beta,  for some old environment it may not recognize so need a dummy `setup.py`.

**Comment by larryliu0820** [comment]
@honno can you please help merge this? I don't have access.

**Comment by honno** [comment]
Trivial change that's nice to get in, so merging.

> Yeah `pyproject.toml` is still in beta, for some old environment it may not recognize so need a dummy `setup.py`.

Makes sense!

**Pull request merged**
